### ISSUE TITLE
How to get started with BinBot?

### ISSUE THREAD

**Issue by calebeaires** [MikeAnthonyG/BinBot#1]
I have testing your BinBot bot, but may you help us get started with it? What is the command to run the script after all is installed (api + binance python)?

**Comment by MikeAnthonyG** [comment]
Hey. I am currently swamped with work. This weekend, I will write documentation, provide use cases, issues, and common pitfalls. I apologize for the delay.

**Comment by MikeAnthonyG** [comment]
First off, I believe the original algorithm for finding opportunities is no longer viable. There are too many bots that will snag your market order first so you will have to insert redundancies to find the current bid/ask price and probably lower any chance of profit. 

You can write a simple script and save it as simple_binbot.py and run it.

import BinBot as bb
bot = bb.BinBot()
bot.hunt(1000, 0.01)

Or if you use an IDE, you can run it in console (eg IPython console). I suggest reading through the code to see what additional methods your bot will require. It is no longer as simple as running bot.hunt().
