### ISSUE TITLE
fully auto triangular arbitrage 

### ISSUE THREAD

**Issue by onthetunnel** [MikeAnthonyG/BinBot#4]
Hello , if this project can do :
fully automatic monitoring and auto multiply total amount of btc(binance minimum order limit is 0.001 Btc) and auto order 3 or more profit road(after calc the higher profit of triangular arbitrage pair like :
road1 :BTC-XX1-ETH-BTC 0.02% profit
road2 : BTC-XX2-ETH-BTC 0.018% profit
road3 : BTC-XX3-BNB-BTC 0.011% profit ) on few second and 24/7. running without problem or crash , i will donate 0.005-0.01 BTC , Hope someone can do this work , Thanks You !

**Comment by MikeAnthonyG** [comment]
You could try with the Floyd-Warshall method but you will not get those returns. This project was more for fun than profit.

**Comment by onthetunnel** [comment]
Hello Thanks You for your reply ! 
i run this Floyd-Warshall using window and no see any order place on my binance acc, and the bb.hunt after auto order some coin and it show me no fund ,these altcoin stuck on my binance acc...
can you tell me why this awesome project cannot profitable,  hope you can tweak it ,is awesome project compared to other works on binance and i can give you some btc ... Thanks You !

**Comment by MikeAnthonyG** [comment]
I would hold off using Hunt for two weeks. I'll update it in the meantime. Floyd-Warshall hunts but will have difficulty finding opportunities because the markets on binance are pretty efficient.

You can get altcoins stuck that won't sell into ETH or BTC if someone else fulfills the market order before you. I'll update it and get back to you.

**Comment by onthetunnel** [comment]
OK Thanks You ! i understand the price will swings and loss some coin , but can you explain how to buffer to protect price swings ? anyway if you can complate this difficult work i will send BTC to you .. because crypto triangular arbitrage project is difficult work and hard to find on github and other place. ..Hope you can do this Amazing work ! Thanks You!

**Comment by onthetunnel** [comment]
hope you can update it for Market order , and this is awesomec project !
